version: '3'

services:
  blockchain.net.node:
    image: blockchain.net.node
    volumes:
       - D:\Docker\Blockchain.NET\Data:/app/Data
    ports:
      - 5000:80
      - 1234:1234
    build:
      context: .
      dockerfile: Blockchain.NET.Node/Dockerfile
