version: '3'

services:
  blockchain.net.node:
    image: blockchain.net.node
    volumes:
       - D:\docker\blockchaindotnet:/app/Data
    ports:
      - 5001:80
    build:
      context: .
      dockerfile: Blockchain.NET.Node/Dockerfile
